### ISSUE TITLE
Singularize not defined reference error

### ISSUE THREAD

**Issue by RyanLangston** [thaalesalves/aid-scripts#2]
Tried using the inventory example, after pasting everything in, I get an error saying

Error:
ReferenceError: singularize is not defined
ReferenceError: singularize is not defined
    at addToInventory (vm.js:117:21)
    at modifier (vm.js:271:5)
    at vm.js:332:1
    at Script.runInContext (vm.js:143:18)
    at /app/node_modules/vm2/lib/main.js:851:53
    at timeout_bridge.js:1:1
    at Script.runInContext (vm.js:143:18)
    at doWithTimeout (/app/node_modules/vm2/lib/main.js:467:17)
    at VM.run (/app/node_modules/vm2/lib/main.js:849:10)
    at Object.exports.stringModifier (/app/helpers/scripting/Sandbox.ts:87:23)
Im hopeless in js and i was hoping you could help

**Comment by thaalesalves** [comment]
That's odd. No calls to that function were supposed to be part of the main branch. It seems I PR'd stuff I shouldn't have. I'll look into it later today and give you a feedback. Thank you for reporting the issue!

**Comment by thaalesalves** [comment]
Yes, that was exactly it. I PR'd a call to the function without the actual definition of the function. I just pushed a fix for that. I removed all mentions of that functions from code. It should work now. Thank you! o/
