### ISSUE TITLE
TypeError: text not iterable

### ISSUE THREAD

**Issue by RyanLangston** [thaalesalves/aid-scripts#3]
Umm, me again, I found another error, your welcome? I think

Error:
TypeError: text.match is not a function or its return value is not iterable
TypeError: text.match is not a function or its return value is not iterable
    at grabAllBrackets (vm.js:32:22)
    at modifier (vm.js:314:5)
    at vm.js:422:1
    at Script.runInContext (vm.js:143:18)
    at /app/node_modules/vm2/lib/main.js:851:53
    at timeout_bridge.js:1:1
    at Script.runInContext (vm.js:143:18)
    at doWithTimeout (/app/node_modules/vm2/lib/main.js:467:17)
    at VM.run (/app/node_modules/vm2/lib/main.js:849:10)
    at Object.exports.stringModifier (/app/helpers/scripting/Sandbox.ts:87:23)

**Comment by thaalesalves** [comment]
Please read the instructions shown in the char sheet README. When you use that script (or other scripts merged with it, or even Gnurro's placeholders), it is required that your prompt has stuff between brackets so the info may be gathered and saved to the game's context.

This error occurs when your initial prompt has nothing between brackets to be captured and saved. There are detailed instructions on how to use this script [here](https://github.com/thaalesalves/aid-scripts/tree/main/character-sheet).
